### ISSUE TITLE
Experiment: Find best crash/bug report sdk

### ISSUE THREAD

**Issue by leokaessner** [BreakOutEvent/breakout-ios#1]
As BreakOut-App-Developer IWLT have detailed crash- and bug-reports which I can easily import to GitHub and Monitor all the crashes.

**Comment by kiliankoe** [comment]
Crashlytics has support for integrating directly with Github issues ;)

And hi Leo o/

**Comment by leokaessner** [comment]
Hey @kiliankoe 
thanks for the tip! I already felt in love with it when max showed it to me yesterday. But what about bug reports from users (also concerning the UI). I think instabug would be a good solution?! What do you think?

**Comment by kiliankoe** [comment]
I knew something like that existed, but had no clue where to find it. Thank you! Instabug looks great!

I recently ran across a framework that basically does the typical shake gesture as well and creates a screenshot, but leaves everything else to you. I'd much prefer not having to send out stuff manually though :D
