### ISSUE TITLE
as a user IWLT have 1Password integration on login

### ISSUE THREAD

**Issue by alexkaessner** [BreakOutEvent/breakout-ios#106]
Would be nice to have the official 1Password integration via the button next to the passcode textfield.

![ios_login](https://cloud.githubusercontent.com/assets/6615076/24074611/572c341a-0c0c-11e7-9d69-a03c95c740dd.png)

**Comment by nerdsupremacist** [comment]
This was done for beta build 6 or 7 (I forgot)
