### ISSUE TITLE
Welcome Screen (Temporarily during registration time)

### ISSUE THREAD

**Issue by leokaessner** [BreakOutEvent/breakout-ios#27]
As user IWLT see a welcome screen after app start as long as the full feature set of the app isn't available.

**Comment by alexkaessner** [comment]
Here's a way to color tint images in iOS: http://stackoverflow.com/questions/19274789/how-can-i-change-image-tintcolor-in-ios-and-watchkit

**Comment by alexkaessner** [comment]
This is interesting as well, related to color tinting images/icons in Xcode: http://stackoverflow.com/questions/19517334/modify-uiimage-renderingmode-from-storyboard-xib-file

**Comment by leokaessner** [comment]
The basic storyboard and code is ready. Missing texts and translations are added with issue #33 later.
