### ISSUE TITLE
Publish documentation using jazzy

### ISSUE THREAD

**Issue by dsymhoven** [BreakOutEvent/breakout-ios#91]

**Comment by florianschmidt1994** [comment]
What is the current state of the documentation? I assume builds are done locally and the output gets pushed with the corresponding commits? Is the documentation now published using the GitHub Pages or findable via the README?

**Comment by nerdsupremacist** [comment]
You're right. They are published with GH-Pages and we decide when the page should be updated by rendering it locally. It should be done often though. The Page will reflect the state of the Documentation in the master branch: http://breakoutevent.github.io/breakout-ios/

**Comment by florianschmidt1994** [comment]
Nice! I would say this issue could be closed then, as the setup for publishing documentation is complete?
