### ISSUE TITLE
Run build and tests on travis-ci.org

### ISSUE THREAD

**Issue by florianschmidt1994** [BreakOutEvent/breakout-ios#93]
This needs setup of travis hooks on GH, the travis.yml file and the build process in general

**Comment by nerdsupremacist** [comment]
@dsymhoven @florianschmidt1994 Ok. I'm wondering what to do with the PrivateConstants file when it comes to testing. I'm pretty sure that the repo won't build without it...

**Comment by florianschmidt1994** [comment]
travis-ci.org allows encrypting sensitive files with a public/private key pair. This setup works very well, as it is already in use at breakoutevent/backend
See https://docs.travis-ci.com/user/encryption-keys/
